---
fixtures:
  repositories:
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    useradd: https://github.com/simp/pupmod-simp-useradd
  symlinks:
    compliance_markup: "#{source_dir}"
