---
language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.0
  - 2.2.1
script:
    - 'bundle exec rake validate'
    - 'bundle exec rake lint'
    - 'bundle exec rake spec'
    - 'bundle exec rake metadata'

env:
  global: 
    - STRICT_VARIABLES=yes
    - TRUSTED_NODE_DATA=yes
  matrix:
  # NOTE: `:environmentpath` was not supported before Puppet 3.5
    - PUPPET_VERSION="~> 3.8.0"
    - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
    - PUPPET_VERSION="~> 4.2.0"
matrix:
  fast_finish: true

  # Ruby 2.1.0
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.8.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 4.2.0"

  # Ruby 2.2.1
  - rvm: 2.2.1
    env: PUPPET_VERSION="~> 3.8.0"
  - rvm: 2.2.1
    env: PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - rvm: 2.2.1
    env: PUPPET_VERSION="~> 4.2.0"
